services:
  postgresql:
    image: postgres:16
    container_name: postgres-pismo-application
    restart: always
    environment:
      POSTGRES_DB: pismo
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    command: "-url=jdbc:postgresql://postgresql:5432/pismo -schemas=public -user=username -password=password migrate"
    volumes:
      - ../src/main/resources/migrations:/flyway/sql
    depends_on:
      - postgresql

networks:
  default:
    name: local-network